# Generated by Django 6.0.5 on 2026-05-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=500, unique=True)),
                ('target_url', models.URLField(help_text='Upstream base URL, e.g. http://192.168.1.2:8000', max_length=2048)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-prefix'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System configuration',
            },
        ),
        migrations.CreateModel(
            name='NodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_status', to='gateway.proxyroute')),
            ],
            options={
                'verbose_name_plural': 'Node statuses',
            },
        ),
        migrations.CreateModel(
            name='ProxyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=16)),
                ('path', models.TextField()),
                ('target_url', models.TextField()),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('response_headers', models.JSONField(default=dict)),
                ('latency_ms', models.FloatField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='gateway.proxyroute')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'method'], name='gateway_pro_created_5e1c8a_idx')],
            },
        ),
    ]
