# Generated by Django 6.0.5 on 2026-05-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparent_proxy_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proxylog',
            new_name='transparent_created_8cd6c2_idx',
            old_name='gateway_pro_created_5e1c8a_idx',
        ),
    ]
